import { Transfer, TransferMetrics, TransferStatus, CriticalTransfer, SuggestedTransfer, CompletedTransfer } from './types';

// Mock user for TechComponents International
export const mockUser = {
  id: 'USER-001',
  name: 'Michael Chen',
  role: 'Supply Chain Manager',
  company: 'TechComponents International',
  email: 'michael.chen@techcomponents.com',
  avatar: '/assets/images/avatars/michael-chen.jpg',
};

// Mock transfer metrics
export const mockTransferMetrics: TransferMetrics = {
  inbound: { count: 24, value: 1250000 },
  outbound: { count: 18, value: 980000 },
  inCustoms: 7,
  awaitingQC: 12,
  successRate: 94.5,
  successRateChange: 2.3,
  avgTransitTime: 4.2,
  totalActive: 42,
  totalValueInTransit: 2230000,
  pendingApprovals: 8,
  critical: 4
};

// Mock analytics metrics
export const mockAnalyticsMetrics = {
  totalTransfers: 156,
  pendingTransfers: 23,
  completedTransfers: 129,
  criticalTransfers: 4,
  avgProcessingTime: '4.5 days',
  onTimeDelivery: 94,
  transferVolume: '$2.4M',
  transferGrowth: '+12.5%',
};

// Mock critical transfers
export const criticalTransfers: CriticalTransfer[] = [
  {
    id: 'TECI-9544',
    description: 'Seoul Microchips → Austin',
    reason: 'Customs documentation incomplete. Shipment held at port of entry.',
    suggestedAction: 'Submit missing HS codes and certificate of origin',
    escalationContact: 'Sarah Kim, Customs Compliance',
  },
  {
    id: 'TECI-9547',
    description: 'Austin → MediTech Devices',
    reason: 'Temperature excursion detected in transit. Potential product damage.',
    suggestedAction: 'Initiate quality check protocol and notify customer',
    escalationContact: 'David Rodriguez, Quality Control',
  },
  {
    id: 'TECI-9550',
    description: 'Guadalajara → Rotterdam',
    reason: 'Shipment delayed by 3+ days. Customer SLA at risk.',
    suggestedAction: 'Expedite shipping and update customer with new ETA',
    escalationContact: 'Emma Johnson, Customer Relations',
  },
  {
    id: 'TECI-9552',
    description: 'Singapore → San Jose',
    reason: 'Missing verification signatures for controlled items.',
    suggestedAction: 'Obtain required signatures from authorized personnel',
    escalationContact: 'James Wong, Compliance Officer',
  },
];

// Mock suggested transfers
export const suggestedTransfers: SuggestedTransfer[] = [
  {
    id: 'ST-001',
    description: 'Low stock of 5nm Microcontrollers at Austin facility',
    currentStock: 125,
    recommendedTransfer: 500,
    sourceFacility: 'Seoul Manufacturing',
    destinationFacility: 'Austin Warehouse',
    estimatedCost: 12500,
    benefit: 'Prevent production stoppage for Q3 orders',
  },
  {
    id: 'ST-002',
    description: 'Excess inventory of Display Modules at Rotterdam',
    currentStock: 1200,
    recommendedTransfer: 800,
    sourceFacility: 'Rotterdam Distribution',
    destinationFacility: 'Guadalajara Assembly',
    estimatedCost: 9800,
    benefit: 'Balance inventory and reduce storage costs',
  },
  {
    id: 'ST-003',
    description: 'Critical shortage of Power ICs at Singapore',
    currentStock: 50,
    recommendedTransfer: 350,
    sourceFacility: 'Taipei Supplier',
    destinationFacility: 'Singapore Assembly',
    estimatedCost: 15200,
    benefit: 'Avoid $120K in late delivery penalties',
  },
];

// Mock completed transfers
export const completedTransfers: CompletedTransfer[] = [
  {
    id: 'TECI-9530',
    from: 'Taipei Semiconductor',
    to: 'Austin Assembly',
    completionDate: '2023-06-15T14:30:00Z',
    value: 245000,
    verificationStatus: 'VERIFIED',
    timeToComplete: 3.5,
    exceptions: 'None',
  },
  {
    id: 'TECI-9525',
    from: 'Austin Warehouse',
    to: 'MediTech Devices',
    completionDate: '2023-06-12T09:15:00Z',
    value: 189500,
    verificationStatus: 'VERIFIED',
    timeToComplete: 2.8,
    exceptions: 'Customs delay (1 day)',
  },
  {
    id: 'TECI-9518',
    from: 'Seoul Manufacturing',
    to: 'Rotterdam Distribution',
    completionDate: '2023-06-08T16:45:00Z',
    value: 312000,
    verificationStatus: 'UNVERIFIED',
    timeToComplete: 5.2,
    exceptions: 'Missing QC signature',
  },
];

// Mock transfer status pipeline
export const transferStatusPipeline = [
  { status: 'SCHEDULED', count: 3 },
  { status: 'IN_PREPARATION', count: 4 },
  { status: 'IN_TRANSIT', count: 6 },
  { status: 'IN_CUSTOMS', count: 2 },
  { status: 'QUALITY_CHECK', count: 3 },
  { status: 'AWAITING_APPROVAL', count: 4 },
];

// Mock transfers
export const mockTransfers: Transfer[] = [
  {
    id: 'TECI-9560',
    type: 'INBOUND',
    from: {
      id: 'LOC-001',
      name: 'Taipei Semiconductor',
      location: 'Taipei, Taiwan',
    },
    to: {
      id: 'LOC-002',
      name: 'Austin Warehouse',
      location: 'Austin, TX, USA',
    },
    items: [
      {
        id: 'ITEM-001',
        name: '5nm Microcontrollers',
        quantity: 1000,
        unitPrice: 120,
        totalValue: 120000,
        serialNumber: 'SN-MC5-1000',
        digitalTwinId: 'DT-MC5-1000',
        thumbnail: '/assets/images/items/microcontroller.jpg',
      },
      {
        id: 'ITEM-002',
        name: 'Power Management ICs',
        quantity: 2500,
        unitPrice: 45,
        totalValue: 112500,
        serialNumber: 'SN-PMIC-2500',
        digitalTwinId: 'DT-PMIC-2500',
        thumbnail: '/assets/images/items/power-ic.jpg',
      },
    ],
    totalValue: 232500,
    dateInitiated: '2023-06-20T08:00:00Z',
    expectedArrival: '2023-06-25T16:00:00Z',
    status: 'SCHEDULED',
    statusUpdateTime: '2023-06-20T08:00:00Z',
    blockchainTxId: '0x8a7d56b5e7c4f3e9d1e5f6a8b7c9d0e1f2a3b4c5',
    priority: 'HIGH',
    notes: 'Critical components for Q3 production',
    documents: [
      {
        id: 'DOC-001',
        name: 'Commercial Invoice',
        url: '/documents/TECI-9560/invoice.pdf',
      },
      {
        id: 'DOC-002',
        name: 'Packing List',
        url: '/documents/TECI-9560/packing-list.pdf',
      },
    ],
    smartContract: {
      id: 'SC-001',
      status: 'ACTIVE',
      paymentTerms: 'Net 30',
      paymentMethod: 'USDC',
      paymentAmount: 232500,
      paymentStatus: 'PENDING',
      triggerCondition: 'VERIFIED_RECEIPT',
    },
    verifications: [
      {
        step: 'CREATION',
        verified: true,
        verifier: 'Michael Chen',
        timestamp: '2023-06-20T08:00:00Z',
      },
      {
        step: 'SHIPPING',
        verified: false,
        verifier: '',
        timestamp: '',
      },
    ],
    timeline: [
      {
        event: 'Transfer Created',
        timestamp: '2023-06-20T08:00:00Z',
        actor: 'Michael Chen',
        location: 'Austin, TX',
        notes: 'Initial transfer creation',
      },
      {
        event: 'Documents Generated',
        timestamp: '2023-06-20T08:15:00Z',
        actor: 'System',
        notes: 'Commercial invoice and packing list generated',
      },
    ],
    isCritical: false,
  },
  {
    id: 'TECI-9559',
    type: 'OUTBOUND',
    from: {
      id: 'LOC-002',
      name: 'Austin Warehouse',
      location: 'Austin, TX, USA',
    },
    to: {
      id: 'LOC-003',
      name: 'MediTech Devices',
      location: 'Boston, MA, USA',
    },
    items: [
      {
        id: 'ITEM-003',
        name: 'Medical Grade Displays',
        quantity: 200,
        unitPrice: 350,
        totalValue: 70000,
        serialNumber: 'SN-MGD-200',
        digitalTwinId: 'DT-MGD-200',
        thumbnail: '/assets/images/items/medical-display.jpg',
      },
      {
        id: 'ITEM-004',
        name: 'Sensor Arrays',
        quantity: 500,
        unitPrice: 85,
        totalValue: 42500,
        serialNumber: 'SN-SA-500',
        digitalTwinId: 'DT-SA-500',
        thumbnail: '/assets/images/items/sensor-array.jpg',
      },
    ],
    totalValue: 112500,
    dateInitiated: '2023-06-19T14:30:00Z',
    expectedArrival: '2023-06-22T12:00:00Z',
    status: 'IN_TRANSIT',
    statusUpdateTime: '2023-06-20T09:45:00Z',
    priority: 'MEDIUM',
    notes: 'Customer order #MED-2023-0568',
    documents: [
      {
        id: 'DOC-003',
        name: 'Commercial Invoice',
        url: '/documents/TECI-9559/invoice.pdf',
      },
      {
        id: 'DOC-004',
        name: 'Bill of Lading',
        url: '/documents/TECI-9559/bill-of-lading.pdf',
      },
    ],
    smartContract: {
      id: 'SC-002',
      status: 'ACTIVE',
      paymentTerms: 'Net 15',
      paymentMethod: 'TRADITIONAL',
      paymentAmount: 112500,
      paymentStatus: 'PENDING',
      triggerCondition: 'VERIFIED_RECEIPT',
    },
    verifications: [
      {
        step: 'CREATION',
        verified: true,
        verifier: 'Michael Chen',
        timestamp: '2023-06-19T14:30:00Z',
      },
      {
        step: 'SHIPPING',
        verified: true,
        verifier: 'Logistics Team',
        timestamp: '2023-06-20T09:45:00Z',
      },
    ],
    timeline: [
      {
        event: 'Transfer Created',
        timestamp: '2023-06-19T14:30:00Z',
        actor: 'Michael Chen',
        location: 'Austin, TX',
        notes: 'Initial transfer creation',
      },
      {
        event: 'Picked for Shipping',
        timestamp: '2023-06-20T08:30:00Z',
        actor: 'Warehouse Team',
        location: 'Austin, TX',
        notes: 'Items picked and packed',
      },
      {
        event: 'Shipped',
        timestamp: '2023-06-20T09:45:00Z',
        actor: 'FastFreight Logistics',
        location: 'Austin, TX',
        notes: 'Shipment picked up by carrier',
      },
    ],
    isCritical: false,
  },
  {
    id: 'TECI-9558',
    type: 'INBOUND',
    from: {
      id: 'LOC-004',
      name: 'Seoul Microchips',
      location: 'Seoul, South Korea',
    },
    to: {
      id: 'LOC-002',
      name: 'Austin Warehouse',
      location: 'Austin, TX, USA',
    },
    items: [
      {
        id: 'ITEM-005',
        name: 'Memory Modules',
        quantity: 5000,
        unitPrice: 25,
        totalValue: 125000,
        serialNumber: 'SN-MM-5000',
        digitalTwinId: 'DT-MM-5000',
        thumbnail: '/assets/images/items/memory-module.jpg',
      },
    ],
    totalValue: 125000,
    dateInitiated: '2023-06-18T10:15:00Z',
    expectedArrival: '2023-06-24T14:00:00Z',
    status: 'IN_CUSTOMS',
    statusUpdateTime: '2023-06-21T11:30:00Z',
    priority: 'HIGH',
    notes: 'Expedited shipping required',
    documents: [
      {
        id: 'DOC-005',
        name: 'Commercial Invoice',
        url: '/documents/TECI-9558/invoice.pdf',
      },
      {
        id: 'DOC-006',
        name: 'Customs Declaration',
        url: '/documents/TECI-9558/customs-declaration.pdf',
      },
    ],
    smartContract: null,
    verifications: [
      {
        step: 'CREATION',
        verified: true,
        verifier: 'Michael Chen',
        timestamp: '2023-06-18T10:15:00Z',
      },
      {
        step: 'SHIPPING',
        verified: true,
        verifier: 'Seoul Logistics',
        timestamp: '2023-06-19T09:00:00Z',
      },
      {
        step: 'CUSTOMS_SUBMISSION',
        verified: true,
        verifier: 'Global Customs Broker',
        timestamp: '2023-06-21T11:30:00Z',
      },
    ],
    timeline: [
      {
        event: 'Transfer Created',
        timestamp: '2023-06-18T10:15:00Z',
        actor: 'Michael Chen',
        location: 'Austin, TX',
        notes: 'Initial transfer creation',
      },
      {
        event: 'Shipped from Seoul',
        timestamp: '2023-06-19T09:00:00Z',
        actor: 'Seoul Logistics',
        location: 'Seoul, South Korea',
        notes: 'Shipment departed facility',
      },
      {
        event: 'Arrived at US Customs',
        timestamp: '2023-06-21T11:30:00Z',
        actor: 'Global Customs Broker',
        location: 'Los Angeles, CA',
        notes: 'Shipment being processed by customs',
      },
    ],
    isCritical: true,
    criticalReason: 'Customs documentation incomplete. Shipment held at port of entry.',
  },
  {
    id: 'TECI-9557',
    type: 'INTERNAL',
    from: {
      id: 'LOC-002',
      name: 'Austin Warehouse',
      location: 'Austin, TX, USA',
    },
    to: {
      id: 'LOC-005',
      name: 'Austin Assembly',
      location: 'Austin, TX, USA',
    },
    items: [
      {
        id: 'ITEM-006',
        name: 'Circuit Boards',
        quantity: 1500,
        unitPrice: 65,
        totalValue: 97500,
        serialNumber: 'SN-CB-1500',
        digitalTwinId: 'DT-CB-1500',
        thumbnail: '/assets/images/items/circuit-board.jpg',
      },
      {
        id: 'ITEM-007',
        name: 'Connector Sets',
        quantity: 3000,
        unitPrice: 12,
        totalValue: 36000,
        serialNumber: 'SN-CS-3000',
        digitalTwinId: 'DT-CS-3000',
        thumbnail: '/assets/images/items/connector-set.jpg',
      },
    ],
    totalValue: 133500,
    dateInitiated: '2023-06-20T11:00:00Z',
    expectedArrival: '2023-06-21T11:00:00Z',
    status: 'QUALITY_CHECK',
    statusUpdateTime: '2023-06-21T09:30:00Z',
    priority: 'MEDIUM',
    notes: 'Internal transfer for production line',
    documents: [
      {
        id: 'DOC-007',
        name: 'Transfer Manifest',
        url: '/documents/TECI-9557/manifest.pdf',
      },
    ],
    smartContract: null,
    verifications: [
      {
        step: 'CREATION',
        verified: true,
        verifier: 'Michael Chen',
        timestamp: '2023-06-20T11:00:00Z',
      },
      {
        step: 'SHIPPING',
        verified: true,
        verifier: 'Warehouse Team',
        timestamp: '2023-06-21T08:15:00Z',
      },
      {
        step: 'QUALITY_CHECK',
        verified: false,
        verifier: '',
        timestamp: '',
      },
    ],
    timeline: [
      {
        event: 'Transfer Created',
        timestamp: '2023-06-20T11:00:00Z',
        actor: 'Michael Chen',
        location: 'Austin, TX',
        notes: 'Initial transfer creation',
      },
      {
        event: 'Items Picked',
        timestamp: '2023-06-21T08:15:00Z',
        actor: 'Warehouse Team',
        location: 'Austin Warehouse, TX',
        notes: 'Items picked for internal transfer',
      },
      {
        event: 'Arrived at Assembly',
        timestamp: '2023-06-21T09:30:00Z',
        actor: 'Assembly Team',
        location: 'Austin Assembly, TX',
        notes: 'Items received, pending quality check',
      },
    ],
    isCritical: false,
  },
  {
    id: 'TECI-9556',
    type: 'OUTBOUND',
    from: {
      id: 'LOC-002',
      name: 'Austin Warehouse',
      location: 'Austin, TX, USA',
    },
    to: {
      id: 'LOC-006',
      name: 'ElectroTech Solutions',
      location: 'San Jose, CA, USA',
    },
    items: [
      {
        id: 'ITEM-008',
        name: 'Processor Units',
        quantity: 300,
        unitPrice: 210,
        totalValue: 63000,
        serialNumber: 'SN-PU-300',
        digitalTwinId: 'DT-PU-300',
        thumbnail: '/assets/images/items/processor.jpg',
      },
      {
        id: 'ITEM-009',
        name: 'Cooling Systems',
        quantity: 300,
        unitPrice: 85,
        totalValue: 25500,
        serialNumber: 'SN-CS-300',
        digitalTwinId: 'DT-CS-300',
        thumbnail: '/assets/images/items/cooling-system.jpg',
      },
    ],
    totalValue: 88500,
    dateInitiated: '2023-06-19T15:45:00Z',
    expectedArrival: '2023-06-22T16:00:00Z',
    status: 'AWAITING_APPROVAL',
    statusUpdateTime: '2023-06-21T14:00:00Z',
    priority: 'LOW',
    notes: 'Customer order #ETS-2023-0125',
    documents: [
      {
        id: 'DOC-008',
        name: 'Commercial Invoice',
        url: '/documents/TECI-9556/invoice.pdf',
      },
      {
        id: 'DOC-009',
        name: 'Shipping Label',
        url: '/documents/TECI-9556/shipping-label.pdf',
      },
    ],
    smartContract: {
      id: 'SC-003',
      status: 'ACTIVE',
      paymentTerms: 'Net 30',
      paymentMethod: 'SHELL',
      paymentAmount: 88500,
      paymentStatus: 'PENDING',
      triggerCondition: 'VERIFIED_RECEIPT',
    },
    verifications: [
      {
        step: 'CREATION',
        verified: true,
        verifier: 'Michael Chen',
        timestamp: '2023-06-19T15:45:00Z',
      },
      {
        step: 'SHIPPING',
        verified: true,
        verifier: 'Warehouse Team',
        timestamp: '2023-06-20T10:30:00Z',
      },
      {
        step: 'RECEIPT',
        verified: false,
        verifier: '',
        timestamp: '',
      },
    ],
    timeline: [
      {
        event: 'Transfer Created',
        timestamp: '2023-06-19T15:45:00Z',
        actor: 'Michael Chen',
        location: 'Austin, TX',
        notes: 'Initial transfer creation',
      },
      {
        event: 'Shipped',
        timestamp: '2023-06-20T10:30:00Z',
        actor: 'Warehouse Team',
        location: 'Austin, TX',
        notes: 'Shipment departed facility',
      },
      {
        event: 'Delivered',
        timestamp: '2023-06-21T14:00:00Z',
        actor: 'Express Shipping',
        location: 'San Jose, CA',
        notes: 'Delivered to recipient, awaiting approval',
      },
    ],
    isCritical: false,
  },
]; 